// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.1.0.0
//      SpecFlow Generator Version:3.1.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ExperimentSpecflow.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class GradeCalculatorFeature : object, Xunit.IClassFixture<GradeCalculatorFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "GradeCalculator.feature"
#line hidden
        
        public GradeCalculatorFeature(GradeCalculatorFeature.FixtureData fixtureData, ExperimentSpecflow_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "GradeCalculator", "\tIn order to ป้องกันข้อผิดพลาดในการตัดเกรดของช่วงคะแนนต่างๆ\r\n\tAs a อาจารย์\r\n\tI wa" +
                    "nt to ให้เกรดนักเรียนจากคะแนนสอบ", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "MinScore",
                        "Grade"});
            table1.AddRow(new string[] {
                        "91",
                        "A"});
            table1.AddRow(new string[] {
                        "81",
                        "B"});
            table1.AddRow(new string[] {
                        "71",
                        "C"});
            table1.AddRow(new string[] {
                        "61",
                        "D"});
            table1.AddRow(new string[] {
                        "0",
                        "F"});
#line 7
 testRunner.Given("เกณฑ์การประเมินเกรดในระบบเป็นดังนี้", ((string)(null)), table1, "Given ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="ใส่ข้อมูลที่ได้คะแนนต่ำกว่า 60 จะต้องได้เกรด F")]
        [Xunit.TraitAttribute("FeatureTitle", "GradeCalculator")]
        [Xunit.TraitAttribute("Description", "ใส่ข้อมูลที่ได้คะแนนต่ำกว่า 60 จะต้องได้เกรด F")]
        [Xunit.InlineDataAttribute("30", "F", new string[0])]
        [Xunit.InlineDataAttribute("60", "F", new string[0])]
        [Xunit.InlineDataAttribute("51", "F", new string[0])]
        public virtual void ใสขอมลทไดคะแนนตำกวา60จะตองไดเกรดF(string score, string expectedGrade, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ใส่ข้อมูลที่ได้คะแนนต่ำกว่า 60 จะต้องได้เกรด F", null, exampleTags);
#line 15
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
#line 16
 testRunner.Given(string.Format("นักเรียนได้คะแนนสอบ \'{0}\' คะแนน", score), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 17
 testRunner.When("ทำการประเมินเกรด", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 18
 testRunner.Then(string.Format("ผลการประเมินจะต้องได้เกรด \'{0}\'", expectedGrade), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="ใส่ข้อมูลที่ได้คะแนนตั้งแต่ 91 ขึ้นไปจะต้องได้เกรด A")]
        [Xunit.TraitAttribute("FeatureTitle", "GradeCalculator")]
        [Xunit.TraitAttribute("Description", "ใส่ข้อมูลที่ได้คะแนนตั้งแต่ 91 ขึ้นไปจะต้องได้เกรด A")]
        [Xunit.InlineDataAttribute("91", new string[0])]
        [Xunit.InlineDataAttribute("99", new string[0])]
        [Xunit.InlineDataAttribute("100", new string[0])]
        public virtual void ใสขอมลทไดคะแนนตงแต91ขนไปจะตองไดเกรดA(string score, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ใส่ข้อมูลที่ได้คะแนนตั้งแต่ 91 ขึ้นไปจะต้องได้เกรด A", null, exampleTags);
#line 26
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
#line 27
 testRunner.Given(string.Format("นักเรียนได้คะแนนสอบ \'{0}\' คะแนน", score), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 28
 testRunner.When("ทำการประเมินเกรด", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 29
 testRunner.Then("ผลการประเมินจะต้องได้เกรด \'A\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.1.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                GradeCalculatorFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                GradeCalculatorFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
